# Application Properties
spring.application.name=scraping-journals

# Database Configuration
spring.datasource.url=jdbc:h2:mem:scrapingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.max-http-header-size=65536

scraping-dog.api.url=https://api.scrapingdog.com
scraping-dog.api.key=68f9911f610f4cb8e4b1d83e

openrouter.api-base-url: https://openrouter.ai/api/v1
openrouter.api-key: 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